# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SVrXiYqRICpgGkLsIOytMVHLrKfQQEL
"""

import seaborn as sns
sns.set_theme(style="ticks", palette="pastel")

# Load the example tips dataset
tips = sns.load_dataset("tips")

# Draw a nested boxplot to show bills by day and time

tips

"""#EDA (Exploratory Data Analysis)
feature
"""

tips.info()

# df = tips
df = tips.copy

(df['tip'] / df['total_bill']) * 100

df['tip_pct'] >= 20

df['tip_pct'] = (df['tip'] / df['total_bill']) * 100
result = df[(df['tip_pct'] >= 20) & ((df['day'] == 'Sun'))]

tips

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))

sns.histplot(data=tips, x="total_bill", kde=True, bins=20, color="skyblue")
plt.title("[수치형] Total_Bill 단변량 분포(Histplot)")
plt.show()

"""### <font color='red> 지도를 그려서  median_house_value/population 별로 scatter하여 어느지역의 집값이 비싼지 말해줘? 시각화 해줘.

## 캘리포니아 주택 가격 분포 시각화

지도를 사용하여 지역별 `median_house_value`와 `population` 관계를 시각화합니다. 이 분석은 인구 대비 주택 가격이 높은 지역을 식별하는 데 도움이 될 수 있습니다.
"""

import pandas as pd
import plotly.express as px

# CSV 파일 로드
file_path = '/content/sample_data/california_housing_train.csv'
df_housing = pd.read_csv(file_path)

# 데이터프레임의 처음 5행과 정보 출력
print("데이터프레임의 처음 5행:")
display(df_housing.head())

print("\n데이터프레임 정보:")
df_housing.info()

"""데이터를 확인한 결과, `latitude`, `longitude`, `median_house_value`, `population` 칼럼이 존재함을 알 수 있습니다. 이 칼럼들을 사용하여 지리적 분포에 따른 주택 가격과 인구 관계를 시각화하겠습니다."""

# 인구 대비 주택 가격(median_house_value/population)을 나타내는 새로운 칼럼 생성
df_housing['price_per_person'] = df_housing['median_house_value'] / df_housing['population']

# 지도 위에 주택 가격 분포를 시각화
# 'median_house_value'를 색상으로, 'population'을 점의 크기로 매핑합니다.
fig = px.scatter_mapbox(
    df_housing,
    lat="latitude",
    lon="longitude",
    color="median_house_value",
    size="population", # 인구를 점의 크기로 표현
    hover_name="median_house_value", # 마우스를 올렸을 때 주택 가치 표시
    hover_data={'price_per_person': ':.2f'}, # hover_data에 price_per_person 추가
    color_continuous_scale=px.colors.sequential.Viridis, # 색상 스케일 설정
    zoom=4, # 초기 확대 레벨
    title="캘리포니아 지역별 주택 가격 및 인구 분포",
    mapbox_style="carto-positron" # 지도 스타일 설정
)

fig.update_layout(mapbox_bounds={"west": -125, "east": -113, "south": 32, "north": 42})
fig.show()

"""위 지도는 캘리포니아 지역별 `median_house_value`(색상)와 `population`(점 크기)을 보여줍니다. 색상이 진할수록 주택 가격이 높고, 점이 클수록 인구가 많습니다. 또한, 마우스를 올리면 `price_per_person` 값도 확인할 수 있습니다. 이 지도를 통해 어느 지역의 집값이 상대적으로 비싼지 시각적으로 확인할 수 있습니다.

# 본 과제는 `tips` 데이터셋을 활용하여 가장 많은 팁을 받을 수 있는 최적의 요일, 시간대, 손님 유형을 분석했다

분석 결과, 가장 높은 팁을 받을 수 있는 요일은 평균 3.26달러를 기록한 **일요일**이며, 토요일(2.99달러)이 뒤를 이어 평일보다 주말의 팁 지출 성향이 높았다. 시간대별로는 저녁(3.10달러)이 점심(2.73달러)보다 높은 팁을 보였는데, 이는 저녁 식사의 전체 결제 금액이 더 크기 때문이다. 손님 유형 측면에서는 인원수가 많을수록 팁이 비례하여 증가하여 4인 이상 단체 손님(4인: 4.14달러, 6인: 5.23달러)의 팁이 가장 많았으며, 성별 및 흡연 여부에서는 남성 및 비흡연 손님 그룹의 평균 팁이 높게 나타났다.

결론적으로 가장 많은 팁을 받기 위해서는 **일요일 저녁 시간대**에 **4인 이상의 단체 손님**이나 **결제 금액이 큰 남성/비흡연 손님 테이블**을 전담하여 서빙하는 것이 가장 효과적이다.
"""

import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

# Seaborn/Plotly 표준 tips 데이터셋 로드
df = px.data.tips()

# 그래프 스타일 설정
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))

# 1. 요일별 평균 팁 시각화 (일요일이 가장 높음)
sns.barplot(
    data=df,
    x="day",
    y="tip",
    order=["Thur", "Fri", "Sat", "Sun"],
    ax=axes[0],
    errorbar=None,
    palette="Blues_d",
)
axes[0].set_title("Average Tip by Day")
axes[0].set_xlabel("Day of Week")
axes[0].set_ylabel("Mean Tip ($)")

# 2. 시간대별 평균 팁 시각화 (저녁이 더 높음)
sns.barplot(
    data=df,
    x="time",
    y="tip",
    ax=axes[1],
    errorbar=None,
    palette="Oranges_d",
)
axes[1].set_title("Average Tip by Time")
axes[1].set_xlabel("Time of Day")
axes[1].set_ylabel("Mean Tip ($)")

# 3. 손님 인원수별 평균 팁 시각화 (인원수가 많을수록 높아짐)
sns.barplot(
    data=df,
    x="size",
    y="tip",
    ax=axes[2],
    errorbar=None,
    palette="Greens_d",
)
axes[2].set_title("Average Tip by Party Size")
axes[2].set_xlabel("Party Size (People)")
axes[2].set_ylabel("Mean Tip ($)")

plt.tight_layout()
plt.show()

